#!/usr/bin/env python
"""
Command line wrapper for sysstat Converter class
"""
import argparse
import subprocess
import sys
import sysstat

parser = argparse.ArgumentParser(
    description="Convert sysstat collector (sadc) data to something else.")

parser.add_argument('infile', metavar='INPUT', help="binary SA data")
parser.add_argument('--outfile', default=sys.stdout, help='text output')
#parser.add_argument('--format', default='line', help="output format",
#                    choices=sadf_options.keys())
parser.add_argument('--interval', default=1, type=int, help="sampling interval")

args = parser.parse_args()

try:
    converter = sysstat.Converter(args.infile, args.outfile)
    converter.convert()
except OSError, e:
    print e.message
    sys.exit(2)
except subprocess.CalledProcessError, e:
    print 'Subprocess error: {}'.format(e.message)
